config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :garment_host_broadcasts
  resources :broadcasts
  resources :hosts
  resources :garments
  resources :colours
  resources :brands
  resources :type_of_garments

  root 'broadcasts#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/type_of_garment.rb
# == Schema Information
#
# Table name: type_of_garments
#
#  id          :integer          not null, primary key
#  name        :string
#  description :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class TypeOfGarment < ApplicationRecord
    has_many :garments
end

app/controllers/type_of_garments_controller.rb
class TypeOfGarmentsController < ApplicationController
  before_action :set_type_of_garment, only: %i[ show edit update destroy ]

  # GET /type_of_garments or /type_of_garments.json
  def index
    @type_of_garments = TypeOfGarment.all
  end

  # GET /type_of_garments/1 or /type_of_garments/1.json
  def show
  end

  # GET /type_of_garments/new
  def new
    @type_of_garment = TypeOfGarment.new
  end

  # GET /type_of_garments/1/edit
  def edit
  end

  # POST /type_of_garments or /type_of_garments.json
  def create
    @type_of_garment = TypeOfGarment.new(type_of_garment_params)

    respond_to do |format|
      if @type_of_garment.save
        format.html { redirect_to @type_of_garment, notice: "Type of garment was successfully created." }
        format.json { render :show, status: :created, location: @type_of_garment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @type_of_garment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /type_of_garments/1 or /type_of_garments/1.json
  def update
    respond_to do |format|
      if @type_of_garment.update(type_of_garment_params)
        format.html { redirect_to @type_of_garment, notice: "Type of garment was successfully updated." }
        format.json { render :show, status: :ok, location: @type_of_garment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @type_of_garment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /type_of_garments/1 or /type_of_garments/1.json
  def destroy
    @type_of_garment.destroy
    respond_to do |format|
      format.html { redirect_to type_of_garments_url, notice: "Type of garment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_type_of_garment
      @type_of_garment = TypeOfGarment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def type_of_garment_params
      params.require(:type_of_garment).permit(:name, :description)
    end
end

app/helpers/type_of_garments_helper.rb
module TypeOfGarmentsHelper
end

app/views/type_of_garments/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@type_of_garment) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :name
    = f.input :description

  .form-actions
    = f.button :submit

app/views/type_of_garments/edit.html.haml
%h1 Editing type_of_garment

= render 'form'

= link_to 'Show', @type_of_garment
\|
= link_to 'Back', type_of_garments_path

app/views/type_of_garments/index.html.haml
%h1 Listing type_of_garments

%table
  %thead
    %tr
      %th Name
      %th Description
      %th
      %th
      %th

  %tbody
    - @type_of_garments.each do |type_of_garment|
      %tr
        %td= type_of_garment.name
        %td= type_of_garment.description
        %td= link_to 'Show', type_of_garment
        %td= link_to 'Edit', edit_type_of_garment_path(type_of_garment)
        %td= link_to 'Destroy', type_of_garment, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Type of garment', new_type_of_garment_path

app/views/type_of_garments/new.html.haml
%h1 New type_of_garment

= render 'form'

= link_to 'Back', type_of_garments_path

app/views/type_of_garments/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @type_of_garment.name
%p
  %b Description:
  = @type_of_garment.description

= link_to 'Edit', edit_type_of_garment_path(@type_of_garment)
\|
= link_to 'Back', type_of_garments_path