config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :garment_host_broadcasts
  resources :broadcasts
  resources :hosts
  resources :garments
  resources :colours
  resources :brands
  resources :type_of_garments

  root 'broadcasts#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/colour.rb
# == Schema Information
#
# Table name: colours
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Colour < ApplicationRecord
    has_many :garments
end

app/controllers/colours_controller.rb
class ColoursController < ApplicationController
  before_action :set_colour, only: %i[ show edit update destroy ]

  # GET /colours or /colours.json
  def index
    @colours = Colour.all
  end

  # GET /colours/1 or /colours/1.json
  def show
  end

  # GET /colours/new
  def new
    @colour = Colour.new
  end

  # GET /colours/1/edit
  def edit
  end

  # POST /colours or /colours.json
  def create
    @colour = Colour.new(colour_params)

    respond_to do |format|
      if @colour.save
        format.html { redirect_to @colour, notice: "Colour was successfully created." }
        format.json { render :show, status: :created, location: @colour }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @colour.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /colours/1 or /colours/1.json
  def update
    respond_to do |format|
      if @colour.update(colour_params)
        format.html { redirect_to @colour, notice: "Colour was successfully updated." }
        format.json { render :show, status: :ok, location: @colour }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @colour.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /colours/1 or /colours/1.json
  def destroy
    @colour.destroy
    respond_to do |format|
      format.html { redirect_to colours_url, notice: "Colour was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_colour
      @colour = Colour.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def colour_params
      params.require(:colour).permit(:name)
    end
end

app/helpers/colours_helper.rb
module ColoursHelper
end

app/views/colours/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@colour) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :name

  .form-actions
    = f.button :submit

app/views/colours/edit.html.haml
%h1 Editing colour

= render 'form'

= link_to 'Show', @colour
\|
= link_to 'Back', colours_path

app/views/colours/index.html.haml
%h1 Listing colours

%table
  %thead
    %tr
      %th Name
      %th
      %th
      %th

  %tbody
    - @colours.each do |colour|
      %tr
        %td= colour.name
        %td= link_to 'Show', colour
        %td= link_to 'Edit', edit_colour_path(colour)
        %td= link_to 'Destroy', colour, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Colour', new_colour_path

app/views/colours/new.html.haml
%h1 New colour

= render 'form'

= link_to 'Back', colours_path

app/views/colours/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @colour.name

= link_to 'Edit', edit_colour_path(@colour)
\|
= link_to 'Back', colours_path