config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :garment_host_broadcasts
  resources :broadcasts
  resources :hosts
  resources :garments
  resources :colours
  resources :brands
  resources :type_of_garments

  root 'broadcasts#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/brand.rb
# == Schema Information
#
# Table name: brands
#
#  id          :integer          not null, primary key
#  name        :string
#  description :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Brand < ApplicationRecord
    has_many :garments
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_action :set_brand, only: %i[ show edit update destroy ]

  # GET /brands or /brands.json
  def index
    @brands = Brand.all
  end

  # GET /brands/1 or /brands/1.json
  def show
  end

  # GET /brands/new
  def new
    @brand = Brand.new
  end

  # GET /brands/1/edit
  def edit
  end

  # POST /brands or /brands.json
  def create
    @brand = Brand.new(brand_params)

    respond_to do |format|
      if @brand.save
        format.html { redirect_to @brand, notice: "Brand was successfully created." }
        format.json { render :show, status: :created, location: @brand }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /brands/1 or /brands/1.json
  def update
    respond_to do |format|
      if @brand.update(brand_params)
        format.html { redirect_to @brand, notice: "Brand was successfully updated." }
        format.json { render :show, status: :ok, location: @brand }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brands/1 or /brands/1.json
  def destroy
    @brand.destroy
    respond_to do |format|
      format.html { redirect_to brands_url, notice: "Brand was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brand
      @brand = Brand.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def brand_params
      params.require(:brand).permit(:name, :description)
    end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/views/brands/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@brand) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :name
    = f.input :description

  .form-actions
    = f.button :submit

app/views/brands/edit.html.haml
%h1 Editing brand

= render 'form'

= link_to 'Show', @brand
\|
= link_to 'Back', brands_path

app/views/brands/index.html.haml
%h1 Listing brands

%table
  %thead
    %tr
      %th Name
      %th Description
      %th
      %th
      %th

  %tbody
    - @brands.each do |brand|
      %tr
        %td= brand.name
        %td= brand.description
        %td= link_to 'Show', brand
        %td= link_to 'Edit', edit_brand_path(brand)
        %td= link_to 'Destroy', brand, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Brand', new_brand_path

app/views/brands/new.html.haml
%h1 New brand

= render 'form'

= link_to 'Back', brands_path

app/views/brands/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @brand.name
%p
  %b Description:
  = @brand.description

= link_to 'Edit', edit_brand_path(@brand)
\|
= link_to 'Back', brands_path