config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :garment_host_broadcasts
  resources :broadcasts
  resources :hosts
  resources :garments
  resources :colours
  resources :brands
  resources :type_of_garments

  root 'broadcasts#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tv</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%
=begin%>
 <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %> 
<%
=end%>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    
  </head>

  <body>
  
  <%= current_user[:email] if !current_user.blank?%>
  <%
=begin%>
 <%= button_to "text", destroy_user_session_path, {class: 'btn btn-primary'}  %> 
<%
=end%>
  <%= link_to t('sign_out'), destroy_user_session_path, method: :delete %>
  <%= link_to t('middle'), garment_host_broadcasts_path %>
  <%= link_to t('garments'), garments_path %>
  <%= link_to t('type'), type_of_garments_path %>
  <%= link_to t('broadcast'), broadcasts_path %>
  <%= link_to t('host'), hosts_path %> 
  <%= yield %>
  </body>
</html>